### ISSUE TITLE
How do I use getServerSession() ? 

### ISSUE THREAD

**Issue by cosbgn** [Hebilicious/authjs-nuxt#10]
I keep getting: `"Cannot read properties of undefined (reading 'trustHost')"`

Trying with: 

```js
import { getServerSession } from '#auth'
const session = await getServerSession(event)
```

**Comment by Hebilicious** [comment]
Hi, can you tell me more about where you are trying to read it ? This is a server only function so it can't be called in client code.
If you need the session, you should grab it from the `useAuth()` composable.

**Comment by cosbgn** [comment]
I use it server side to know who is the user. E.g. I want to get from my database all the posts form the user. 
I've figured that I can do: 

```js

export default defineEventHandler(async (event) => {
	const session = await getServerSession(event, authOptions)
})

```

It seems a bit repetitive though to always pass the authOptions, on sidebase-auth I could simply do `await getServerSession(event)`

**Comment by Hebilicious** [comment]
> I use it server side to know who is the user. E.g. I want to get from my database all the posts form the user. I've figured that I can do:
> 
> ```js
> export default defineEventHandler(async (event) => {
> 	const session = await getServerSession(event, authOptions)
> })
> ```
> 
> It seems a bit repetitive though to always pass the authOptions, on sidebase-auth I could simply do `await getServerSession(event)`

I see your use-case, this could be made simpler indeed. As a workaround, you can create your own helper like this. 

```ts
//server/utils.ts
import { getServerSession } from "#auth"
import { authOptions } from "~/server/api/auth/[...]"
 
export const getSession = (event) => getServerSession(event, authOptions)
```

**Comment by cosbgn** [comment]
Yes this is exactly what I do!
