### ISSUE TITLE
`getServerSession()` throws a `[nuxt] [request error] [unhandled] [500] No Origin found` even though origin is set

### ISSUE THREAD

**Issue by jimezesinachi** [Hebilicious/authjs-nuxt#107]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.8.4`
- Nitro Version:   `2.6.3`
- Package Manager:  `pnpm@8.7.6`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `ui`, `alias`, `authJs`, `runtimeConfig`
- Runtime Modules:  `@nuxt/ui@2.8.1`, `@hebilicious/authjs-nuxt@0.3.0`, `vue-email/nuxt`
- Build Modules:    `-`

### Reproduction

Full description of problem below

### Describe the bug

I am making a call to getServerSession() in my API route, like this:

```
import { APIResponseData } from "~/server/utils/types";

import { prisma } from "../../../prisma/db";
import {
  GetUsersInputSchema,
  GlobalQueryResponseOutputSchemaInputType,
} from "~/server/utils/validators";
// import { getAuthSession } from "~/server/utils/admin";
import { getServerSession, getServerToken } from "#auth";
import { authOptions } from "../auth/[...]";

// import protectAdmin from "../../utils/validators/admin";

export default defineEventHandler(async (event) => {
  // await protectAdmin(event);
  const session = await getServerSession(event, authOptions);
  const jwt = await getServerToken(event, authOptions);

  console.log(session, jwt);

  return `API route`;
});
```

It throws this error:

```
[nuxt] [request error] [unhandled] [500] No Origin found ...
  at getServerOrigin (./node_modules/.pnpm/@hebilicious+authjs-nuxt@0.3.0_@auth+core@0.15.0_nuxt@3.7.3/node_modules/@hebilicious/authjs-nuxt/dist/runtime/utils.mjs:15:11)
  at getServerToken (./node_modules/.pnpm/@hebilicious+authjs-nuxt@0.3.0_@auth+core@0.15.0_nuxt@3.7.3/node_modules/@hebilicious/authjs-nuxt/dist/runtime/lib/server.mjs:47:19)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at <anonymous> (./server/api/users/index.get.ts:17:1)
  at async Object.handler (./node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1630:19)
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1840:7)
```

I have set `NEXTAUTH_SECRET` and `NEXTAUTH_URL` in my .env.

And here is my `nuxt.config.ts`:

```
import { resolve } from "node:path";

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@nuxt/ui", "@hebilicious/authjs-nuxt", "vue-email/nuxt"],
  ui: {
    icons: ["logos", "mdi"],
  },

  alias: {
    cookie: resolve(__dirname, "node_modules/cookie"),
  },

  //   Optional default config
  authJs: {
    baseUrl: process.env.NUXT_NEXTAUTH_URL, // should be something like https://www.my-app.com
    verifyClientOnEveryRequest: true,
    //   guestRedirectTo: "/", // where to redirect if the user is authenticated
    //   authenticatedRedirectTo: "/", // where to redirect if the user is not authenticated
  },
  runtimeConfig: {
    authJs: {
      secret: process.env.NUXT_NEXTAUTH_SECRET, // You can generate one with `openssl rand -base64 32`
    },
    discord: {
      clientId: process.env.NUXT_DISCORD_CLIENT_ID,
      clientSecret: process.env.NUXT_DISCORD_CLIENT_SECRET,
    },
    email: {
      senderAddress: process.env.NUXT_EMAIL_SENDER_ADDRESS,
      serverUsername: process.env.NUXT_EMAIL_SERVER_USERNAME,
      serverPassword: process.env.NUXT_EMAIL_SERVER_PASSWORD,
      serverHost: process.env.NUXT_EMAIL_SERVER_HOST,
      serverPort: Number(process.env.NUXT_EMAIL_SERVER_PORT),
    },
    google: {
      clientId: process.env.NUXT_GOOGLE_CLIENT_ID,
      clientSecret: process.env.NUXT_GOOGLE_CLIENT_SECRET,
    },
    organization: {
      name: process.env.NUXT_ORGANIZATION_NAME,
      domain: process.env.NUXT_ORGANIZATION_HOST_DOMAIN,
    },
    public: {
      authJs: {
        baseUrl: process.env.NUXT_NEXTAUTH_URL, // The URL of your deployed app (used for origin Check in production)
        verifyClientOnEveryRequest: true, // whether to hit the /auth/session endpoint on every client request
      },
    },
  },
});
```

I can't figure out why it's still throwing the error.

**Comment by tobychidi** [comment]
There seems to be a missing .env Variable that is required 

`AUTH_ORIGIN`

The docs needs updating.

**Comment by Hebilicious** [comment]
Do you have a reproduction ? I assume this could be something that was introduced in a more recent version of auth.js

**Comment by jimezesinachi** [comment]
> Do you have a reproduction ? https://github.com/Hebilicious/authjs-nuxt/blob/e00d2046f79eb28c300adba6d4be471b8ae05d22/packages/authjs-nuxt/src/runtime/utils.ts#L22C1-L22C1
> 
> If you look at the logic here, it should work if you have a baseUrl properly set. I assume it's because you did not prefix your env variables with `NUXT_`.
> 
> @tobychidi `AUTH_ORIGIN` is undocumented because it's unstable, the name might change later so I wouldn't rely on it too much.

Indeed. Adding the prefixes and the `AUTH_ORIGIN` env variable fixed it for me. Thanks!

**Comment by jimezesinachi** [comment]
Closing this now, as this is not an issue with the plugin.

**Comment by jimezesinachi** [comment]
Closing this now, as this is not an issue with the plugin.

**Comment by orenmizr** [comment]
got this error - i seem to have same config. 

pnpm. added the env: 
NUXT_NEXTAUTH_SECRET=something
NUXT_NEXTAUTH_URL=http://localhost:3000
NUXT_NEXTAUTH_AUTH_ORIGIN=http://localhost:3000

the alias in nuxt config 
 alias: {
    cookie: "cookie",
  },
  
  the ERROR: 
   ERROR  [nuxt] [request error] [unhandled] [500] **No Origin found** ...
  at getServerOrigin (./node_modules/.pnpm/@hebilicious+authjs-nuxt@0.3.5_@auth+core@0.17.0_nuxt@3.11.2_@parcel+watcher@2.4.1_@types+nod_rmmh3nryu6ms5w6ogod5ukuutq/node_modules/@hebilicious/authjs-nuxt/dist/runtime/utils.mjs:15:11)  
  at getServerToken (./node_modules/.pnpm/@hebilicious+authjs-nuxt@0.3.5_@auth+core@0.17.0_nuxt@3.11.2_@parcel+watcher@2.4.1_@types+nod_rmmh3nryu6ms5w6ogod5ukuutq/node_modules/@hebilicious/authjs-nuxt/dist/runtime/lib/server.mjs:47:19)  
  at Object.handler (./server/api/bookmark.post.ts:23:1)  
  at async ./node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:1962:19  
  at async Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:2249:7)

**Comment by Corentin7301** [comment]
Hello,
I had the same issue as @jimezesinachi, adding the environment variable `AUTH_ORIGIN` also fixed the issue for me.
Thanks!
