### ISSUE TITLE
v0.3.1 and v0.3.2 are not in the npm registry

### ISSUE THREAD

**Issue by thunfisch987** [Hebilicious/authjs-nuxt#108]
### Environment

-

### Reproduction

Go to the npm registry and look or install the package (installs 0.3.0)

### Describe the bug

Version 0.3.1 and 0.3.2 are not in the npm registry

**Comment by Hebilicious** [comment]
@thunfisch987 thanks for the heads-up, will fix that with 0.3.3

**Comment by thunfisch987** [comment]
Thanks!

**Comment by Hebilicious** [comment]
done => https://github.com/Hebilicious/authjs-nuxt/releases/tag/v0.3.4
