### ISSUE TITLE
access h3 event in auth.js callback

### ISSUE THREAD

**Issue by imcm7** [Hebilicious/authjs-nuxt#113]
### Environment

- Operating System: Linux
- Node Version: v20.6.1
- Nuxt Version: 3.8.0-28267841.4063b498
- CLI Version: 3.9.1-1695234696.c4b90f7
- Nitro Version: 2.6.3
- Package Manager: bun@1.0.2
- Runtime Modules: @hebilicious/authjs-nuxt@0.3.4

### Reproduction

https://github.com/imcm7/nuxt-db/blob/8362c342a7ddd154255ef8c7c94869a1b80d7673/server/api/%5B...%5D.ts#L77

### Describe the bug

In export `default NuxtAuthHandler(authOptions, runtimeConfig)`, in the `async authorize(credentials, request)` the request is not of typr 'H3Event'.

**Comment by imcm7** [comment]
If I attach some think to event.context I can't get it here. May be only with useEvent();

**Comment by Hebilicious** [comment]
I'm not sure what you're trying to achieve, but you could probably achieve it from not attaching things to `event.context`.
Please provide a reproduction if you want more assistance.

**Comment by imcm7** [comment]
@Hebilicious reproduction is provided

**Comment by Hebilicious** [comment]
> @Hebilicious reproduction is provided

I'm not sure you can use `useEvent` there, but if it's not working, you should refactor your code so that you create a composable similar to your `useDatasource` instead of relying on `event.context`.

**Comment by imcm7** [comment]
> > @Hebilicious reproduction is provided
> 
> I'm not sure you can use `useEvent` there, but if it's not working, you should refactor your code to create a composable similar to `useDatasource` instead of relying on `event.context`.

The idea is to remove `useDatasource`  and use `event.context.em.getEntityReposytory(user)` in controller, services, and router. I do that in all parts of app with success, except NuxtAuthHandler. In it useEvent() works, I thin because I use  experimental async contex.
