### ISSUE TITLE
Argument of type 'NitroRuntimeConfig' is not assignable to parameter of type 'RuntimeConfig'

### ISSUE THREAD

**Issue by imcm7** [Hebilicious/authjs-nuxt#114]
### Environment

- Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.8.0-28267841.4063b498
- CLI Version:      3.9.1-1695234696.c4b90f7
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.2
- Builder:          -
- User Config:      alias, app, colorMode, css, dayjs, devtools, experimental, i18n, image, modules, nitro, runtimeConfig, security, spaLoadingTemplate, ssr, tailwindcss, typescript, viewport, vueEmail
- Runtime Modules:  @hebilicious/authjs-nuxt@0.3.4, @nuxt/image@1.0.0-rc.2, @nuxtjs/color-mode@3.3.0, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @vee-validate/nuxt@4.11.7, @vueuse/nuxt@10.4.1, dayjs-nuxt@1.2.3, nuxt-security@0.14.4, nuxt-viewport@2.0.6, vue3-carousel-nuxt@1.1.0, vue-email/nuxt
- Build Modules:    -

### Reproduction

https://github.com/imcm7/nuxt-db/blob/8362c342a7ddd154255ef8c7c94869a1b80d7673/server/api/%5B...%5D.ts#L95

### Describe the bug

```
const runtimeConfig = useRuntimeConfig();
export default NuxtAuthHandler(authOptions, runtimeConfig); <--- Argument of type 'NitroRuntimeConfig' is not assignable to parameter of type 'RuntimeConfig'.  Type 'NitroRuntimeConfig' is missing the following properties from type 'RuntimeConfig': public, csurf, authJs, github, and 2 more.ts
```

**Comment by Hebilicious** [comment]
@imcm7 Could you confirm that it's working if you ignore types ?

**Comment by imcm7** [comment]
> @imcm7 Could you confirm that it's working if you ts-ignore the types ? Btw make sure that your `nuxt.config.ts` has the necessary properties : https://github.com/imcm7/nuxt-db/blob/8362c342a7ddd154255ef8c7c94869a1b80d7673/nuxt.config.ts

Yes in my local project nuxt auth is configured well and worked some time ago, was able to login and output session data. And that alert I not seen

**Comment by peterbud** [comment]
I experience the same type warning.

On the server side `runtimeConfig()` returns a type `NitroRuntimeConfig`

See nitropack's type definiton:
https://github.com/unjs/nitro/blob/main/src/runtime/config.ts#L19-L21

```typescript
export declare function useRuntimeConfig<T extends NitroRuntimeConfig = NitroRuntimeConfig>(event?: H3Event): T;
```
However the type of the runtime parameter of the function `NuxtAuthHandler` is `RuntimeConfig`

**Comment by imcm7** [comment]
> I experience the same type warning.
> 
> On the server side `runtimeConfig()` returns a type `NitroRuntimeConfig`
> 
> See nitropack's type definiton: https://github.com/unjs/nitro/blob/main/src/runtime/config.ts#L19-L21
> 
> ```ts
> export declare function useRuntimeConfig<T extends NitroRuntimeConfig = NitroRuntimeConfig>(event?: H3Event): T;
> ```
> 
> However the type of the runtime parameter of the function `NuxtAuthHandler` is `RuntimeConfig`

@ts-ignore is your best friend, or bigger enemy
