### ISSUE TITLE
Upgrade @auth/core dependency to include at least 0.16

### ISSUE THREAD

**Issue by thunfisch987** [Hebilicious/authjs-nuxt#117]
### Describe the feature

see title

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
You should be able to use any version of @auth/core. The recommended version is the last one that has be tested though. Is there anything not working on your side ?

**Comment by thunfisch987** [comment]
does that include the new providers that were added since 0.14.0?

**Comment by thunfisch987** [comment]
these new providers are TikTok, Dribbble,

there also seem to be some bugfixes (not important to my projects tho), i don't know if these are important for the peer dependecy or the seperate module

**Comment by cosbgn** [comment]
```
c@mb proj % npm outdated
Package     Current  Wanted  Latest  Location                 Depended by
@auth/core   0.14.0  0.14.0  0.16.1  node_modules/@auth/core  proj
```
I can confirm, when running `npm outdated` it shows as `wanted` version 0.14 - So `npm update` won't update it.

If I try to update it with: `npm i -D @auth/core@0.16.1` it's giving me a lot of warnings:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN node_modules/@auth/core
npm WARN   peer @auth/core@"^0.14.0" from @hebilicious/authjs-nuxt@0.3.4
```
This said, I'm now running 0.16 locally and it all seems to work fine.

**Comment by thunfisch987** [comment]
you can define overrides / resolutions for npm / yarn / pnpm so they ignore the error and install version 0.16 as peer dependecy for authjs-nuxt

i'm personally using bun (at this point) does not have overrides / resolutions implemented
see https://github.com/oven-sh/bun/issues/1134

**Comment by cosbgn** [comment]
<img width="822" alt="image" src="https://github.com/Hebilicious/authjs-nuxt/assets/17546283/eaedc1cf-e5e2-4b21-9d83-17b77b5152ef">

Just FYI v0.16 works locally but fails when deployed to vercel, so it's required 0.14 unless you manually define overrides / resolutions

**Comment by thunfisch987** [comment]
Bun now implements overrides & resolutions so i can just override it :fire:
https://bun.sh/blog/bun-v1.0.6
i still think the newer versions should be included

**Comment by Hebilicious** [comment]
I tend to update the peer dependencies after I had the time to test them with the module ... Once this module move to the official authjs repo this won't be an issue anymore, but for now they will fall out of sync. Please use resolutions/overrides.

**Comment by thunfisch987** [comment]
https://github.com/Hebilicious/authjs-nuxt/releases/tag/v0.3.5
