### ISSUE TITLE
Is not supported resolving ES modules

### ISSUE THREAD

**Issue by imcm7** [Hebilicious/authjs-nuxt#135]
### Environment

- Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.8.3-28342001.8d1fc6c4
- CLI Version:      3.10.1-1700494798.f113a08
- Nitro Version:    2.8.0
- Package Manager:  bun@1.0.7
- Builder:          -
- User Config:      alias, app, colorMode, css, devtools, experimental, i18n, modules, nitro, runtimeConfig, security, spaLoadingTemplate, ssr, tailwindcss, typescript, viewport, vite, vueEmail
- Runtime Modules:  @hebilicious/authjs-nuxt@0.3.5, @nuxtjs/color-mode@3.3.2, @nuxtjs/i18n@8.0.0-rc.5, @nuxtjs/tailwindcss@6.10.0, @pinia/nuxt@0.5.1, @vee-validate/nuxt@4.11.8, @vueuse/nuxt@10.6.1, nuxt-security@0.14.4, nuxt-time@0.1.1, nuxt-viewport@2.0.6, vue3-carousel-nuxt@1.1.0, vue-email/nuxt
- Build Modules:    -

### Reproduction

I updated my project that work prior to last nuxt and start it with bun.
The project is something like that https://github.com/imcm7/nuxt-db

### Describe the bug

 ERROR  [worker reload] [worker init] Directory import '/Project/node/nuxt/happypc/node_modules/@auth/core/lib/actions' is not supported resolving ES modules imported from /Project/node/nuxt/happypc/node_modules/@auth/core/lib/index.js

  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at new NodeError (node:internal/errors:405:5)
  at finalizeResolution (node:internal/modules/esm/resolve:218:11)
  at moduleResolve (node:internal/modules/esm/resolve:836:10)
  at defaultResolve (node:internal/modules/esm/resolve:1034:11)
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:375:12)
  at ModuleLoader.resolve (node:internal/modules/esm/loader:344:25)
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:220:38)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
  at link (node:internal/modules/esm/module_job:84:36)

**Comment by imcm7** [comment]
import * as actions from "./actions";  // <-- may be "./actions/index.js";
import { validateCSRF } from "./actions/callback/oauth/csrf-token.js";

**Comment by Hebilicious** [comment]
Hi @imcm7 , it looks like an issue with your setup. 
If you can provide a minimal reproduction that would be very helpful.
To help you investigate on your own, create a new nuxt project on a fresh directory with the CLI, and make sure everything works. Then add in the module and follow the docs to make sure everything works.
I suspect that you have an issue with your node_modules or your package.json somewhere (it could come from a parent directory)

**Comment by imcm7** [comment]
"name": "@auth/core",
  "version": "0.18.2",
  
  in file @auth/core/lib/index.js
  
  ```
  import renderPage from "./pages/index.js";
  import * as actions from "./actions"; // no index.js
  ```
  
  and in @auth/core/src/lib/index.ts is the same
  
  ```
  import renderPage from "./pages/index.js"
  import * as actions from "./actions"
  ```
  
  But in https://github.com/nextauthjs/next-auth/blob/a3809f6fc44be68a3e6729f5d7f8d0be6b340dd5/packages/core/src/lib/index.ts#L5 all is with index.js

**Comment by imcm7** [comment]
It was updated by @auth mantainers https://github.com/nextauthjs/next-auth/blame/a3809f6fc44be68a3e6729f5d7f8d0be6b340dd5/packages/core/src/lib/index.ts#L5

**Comment by Hebilicious** [comment]
Great. I'll close this then.
