### ISSUE TITLE
Cannot finish the setup with Auth0

### ISSUE THREAD

**Issue by alxpereira** [Hebilicious/authjs-nuxt#159]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.1.0`
- Nuxt Version:     `3.9.3`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `gtag`, `routeRules`, `app`, `alias`, `runtimeConfig`
- Runtime Modules:  `@element-plus/nuxt@1.0.7`, `@nuxtjs/i18n@8.0.0`, `nuxt-gtag@1.1.2`, `@hebilicious/authjs-nuxt@0.3.5`
- Build Modules:    `-`

### Reproduction

Nuxt3 setup with authjs nuxt plugin. 
- cookie alias : YES
- @auth/core : 0.17.0 forced

auth/[...].ts setup as below

```ts
import Auth0Provider from "@auth/core/providers/auth0";
import type { AuthConfig } from "@auth/core/types";
import { NuxtAuthHandler } from "#auth";

const runtimeConfig = useRuntimeConfig();

export const authOptions: AuthConfig = {
  secret: runtimeConfig.authJs.secret,
  theme: {
    logo: "https://nuxt.com/assets/design-kit/logo/icon-green.png",
  },
  providers: [
    Auth0Provider({
      clientId: process.env.AUTH0_CLIENT_ID,
      clientSecret: process.env.AUTH0_SECRET,
      issuer: process.env.AUTH0_BASEURL,
      wellKnown: `https://${process.env.AUTH0_DOMAIN}/.well-known/openid-configuration`,
      authorization: {
        url: `https://${process.env.AUTH0_DOMAIN}/authorize`,
        params: { scope: "openid profile email" },
      },
    }),
  ],
};

export default NuxtAuthHandler(authOptions, runtimeConfig);

```

### Describe the bug

The login page is starting properly, but got this error on callback. 
It tried to test a lot of possible configurations in the Provider setup, but nothing goes properly. 

`OperationProcessingError: "response" is not a conform Authorization Server Metadata response`

Any idea ?

**Comment by outofthisworld** [comment]
Likely a configuration issue. Check none of your env variables are incorrect or coming as empty and that you've provided all the none optional data. Additionally, check your client configuration in auth0.

**Comment by outofthisworld** [comment]
> ```ts
>    issuer: process.env.AUTH0_BASEURL,
>     wellKnown: https://${process.env.AUTH0_DOMAIN}/.well-known/openid-configuration,
> ```

**Comment by alxpereira** [comment]
Thanks, I found the issue, indeed the issuer / wellKnow settings were in collision, the documentation was unclear. 

For the record, here is my final (working) setting : 

```ts

export const authOptions: AuthConfig = {
  secret: runtimeConfig.authJs.secret,
  theme: {
    logo: "https://nuxt.com/assets/design-kit/logo/icon-green.png",
  },
  providers: [
    Auth0Provider({
      clientId: process.env.AUTH0_CLIENT_ID,
      clientSecret: process.env.AUTH0_SECRET,
      issuer: `https://${process.env.AUTH0_DOMAIN}`,
      authorization: {
        url: `https://${process.env.AUTH0_DOMAIN}/authorize`,
        params: { scope: "openid profile email" },
      },
    }),
  ],
};
      
      ```
