### ISSUE TITLE
Unknown route middleware: 'auth'. Valid middleware: .

### ISSUE THREAD

**Issue by janrudowski** [Hebilicious/authjs-nuxt#20]
### Nuxt project info:                                                                                                                                                                                         
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.5
- Builder:          vite
- User Config:      devtools, modules, runtimeConfig, alias
- Runtime Modules:  @hebilicious/authjs-nuxt@0.1.1
- Build Modules:  -

### nuxt.config.ts

```typescript
import { resolve } from "node:path";
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@hebilicious/authjs-nuxt"],
  runtimeConfig: {
    authJs: {
      secret: "secret1234567890", // You can generate one with `openssl rand -base64 32`
    },
    public: {
      authJs: {
        baseUrl: "http://localhost:3000", // The base URL is used for the Origin Check in prod only
        verifyClientOnEveryRequest: true, // whether to hit the /auth/session endpoint on every client request
        guestRedirectTo: "/login",
      },
    },
  },
  alias: {
    cookie: resolve(__dirname, "node_modules/cookie"),
    jose: resolve(__dirname, "node_modules/jose/dist/browser/index.js"),
    "@panva/hkdf": resolve(
      __dirname,
      "node_modules/@panva/hkdf/dist/web/index.js"
    ),
  },
});
```

### Reproduction

**Repo:**
[https://github.com/janrudowski/nuxt-auth-middleware-issue](https://github.com/janrudowski/nuxt-auth-middleware-issue)

There are two routes: /login and index. index is protected with "auth" middleware. Access the login page. Press the log in button.
After redirecting there should be the "500
Unknown route middleware: 'auth'. Valid middleware:  ," error

### Describe the bug

After logging in middleware error is displayed:
```
500
Unknown route middleware: 'auth'. Valid middleware: .
```

### Logs

```sh
{ "url": "/", "statusCode": 500, "statusMessage": "", "message": "Unknown route middleware: 'auth'. Valid middleware: .", "stack": "<pre><span class=\"stack internal\">at E:\\dev\\nuxt\\test\\node_modules\\.pnpm\\nuxt@3.6.1_@types+node@18.0.0\\node_modules\\nuxt\\dist\\pages\\runtime\\plugins\\router.js:126:21</span></pre>" }
```

**Comment by Hebilicious** [comment]
@janrudowski try to clear your site data in your browser devtools. It looks like some old cookie/session is causing the issue.

**Comment by Hebilicious** [comment]
For now you can work around the issue by manually adding the middleware 

```ts
export default defineNuxtRouteMiddleware((to) => {
  if (to.meta.middleware !== "auth-2") return
  const { status } = useAuth()
  if (status.value === "authenticated") return
  const url = useRuntimeConfig()?.public?.authJs?.guestRedirectTo ?? "/"
  return navigateTo(url)
})
```

**Comment by janrudowski** [comment]
@Hebilicious clearing cache doesn't help. but i added the middleware manually (how you suggested) and it works.
thanks!

**Comment by Hebilicious** [comment]
This is probably an issue with Nuxt Kit or Nuxt... Will investigate further.

**Comment by Hebilicious** [comment]
> @Hebilicious clearing cache doesn't help. but i added the middleware manually (how you suggested) and it works. thanks!

I fixed the issue with the following https://github.com/Hebilicious/authjs-nuxt/releases
I also changed the middleware so they can be used with `auth:false`
