### ISSUE TITLE
useAuth: types are any

### ISSUE THREAD

**Issue by yk-sgr** [Hebilicious/authjs-nuxt#22]
It seems like some types can not be inferred.

![image](https://github.com/Hebilicious/authjs-nuxt/assets/24418343/68e48636-4b14-4e7d-8a72-db58b47777d9)

**Comment by Hebilicious** [comment]
Do you get the any type when you use the composable?
This is what I get :
<img width="488" alt="image" src="https://github.com/Hebilicious/authjs-nuxt/assets/13395944/5a294448-bd5f-4acc-9d47-927e0a34ab89">

**Comment by yk-sgr** [comment]
![image](https://github.com/Hebilicious/authjs-nuxt/assets/24418343/e5b28f51-0114-474a-964d-a011cf9a189b)

NodeJS v20.4.0
pnpm 8.6.6
`"@hebilicious/authjs-nuxt": "^0.1.3"`

**Comment by yk-sgr** [comment]
Setup a new project and copied your Getting Started 1:1
Still the same issue.

![image](https://github.com/Hebilicious/authjs-nuxt/assets/24418343/27fc9180-7f25-4372-826a-58d62bcbbd4a)

`package.json`
![image](https://github.com/Hebilicious/authjs-nuxt/assets/24418343/bd0060cb-9879-4c35-b639-524a238c9268)

**Comment by Hebilicious** [comment]
> ![image](https://user-images.githubusercontent.com/24418343/252899741-e5b28f51-0114-474a-964d-a011cf9a189b.png)
> 
> NodeJS v20.4.0 pnpm 8.6.6 `"@hebilicious/authjs-nuxt": "^0.1.3"`

If you can reproduce the issue in a stackblitz that will be very helpful to debug it. The types should come up after nuxt generates the `.nuxt` folder.

**Comment by selemondev** [comment]
Hey there @yk-sgr, to resolve the issue, please follow these steps:

1. Make sure you have the Volar extension installed.

2. Press `command + shift + p` if you are on a Mac, or `ctrl + shift + p` if you are on Windows, to open the command palette.

3. In the command palette, search for `Volar: Restart Vue Server` and select it.

4. After restarting the Vue server, the types will be inferred correctly.

Let me know if this works and if you need any further assistance!

**Comment by Hebilicious** [comment]
> I came across this [stackoverflow.com/questions/74428406/vue-ref-property-not-able-to-infer-type-correctly](https://stackoverflow.com/questions/74428406/vue-ref-property-not-able-to-infer-type-correctly) which actually fixes the issue.
> 
> [yk-sgr/authjs-nuxt@`main`/packages/authjs-nuxt/src/runtime/composables/useAuth.ts](https://github.com/yk-sgr/authjs-nuxt/blob/main/packages/authjs-nuxt/src/runtime/composables/useAuth.ts?rgh-link-date=2023-07-12T09%3A21%3A23Z)
> 
> It leads to this build output:
> 
> `useAuth.d.ts`
> 
> ```ts
> import type { Session } from "@auth/core/types";
> import type { Ref } from "vue";
> import * as auth from "../lib";
> export declare function useAuth(): {
>     session: Readonly<Ref<{
>         readonly user?: {
>             readonly name?: string | null | undefined;
>             readonly email?: string | null | undefined;
>             readonly image?: string | null | undefined;
>         } | undefined;
>         readonly expires: string;
>     } | null>>;
>     user: import("vue").ComputedRef<{
>         name?: string | null | undefined;
>         email?: string | null | undefined;
>         image?: string | null | undefined;
>     } | null>;
>     updateSession: (u: (() => unknown) | Session | null) => void;
>     status: Readonly<Ref<"error" | "loading" | "authenticated" | "unauthenticated">>;
>     signIn: (providerId?: auth.LiteralUnion<import("@auth/core/providers").BuiltInProviderType> | undefined, options?: auth.SignInOptions | undefined, authorizationParams?: auth.SignInAuthorizationParams | undefined) => void;
>     signOut: (options?: auth.SignOutParams<true> | undefined) => Promise<void>;
>     cookies: Ref<Record<string, string> | null>;
>     sessionToken: import("vue").ComputedRef<string>;
>     removeSession: () => void;
> };
> ```
> 
> But I don't know if this is just some weird workaround (I guess so).

Thank you for the investigation ! Do you want to make a PR ? Otherwise I'll add the fix 👍🏽
