### ISSUE TITLE
[feature request] : guest-only middleware

### ISSUE THREAD

**Issue by selemondev** [Hebilicious/authjs-nuxt#34]
### Describe the feature

So far everything is working great except `middlewares`. After a user is authenticated, he or she is redirected to the protected page but the user can STILL ACCESS the login and register page. If the user is NOT authenticated, the middleware WORKS by not letting the authenticated user see the protected page. So my questions are:

1. Is there a built in middleware that can prevent the user from accessing the login and register page once authenticated ?

2. Is this a bug that can be fixed or is it a feature that needs to be implemented ?

3. If the answer to the above 2 questions is `No`. Does it mean I should create a middleware myself?

Also in my `nuxt.config.ts` file, I have set `verifyClientOnEveryRequest: true` and used `definePageMeta({ middleware: 'auth' })` to protect my private pages.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
1. No
2. No it's not a bug, and yes this could be implemented
3. Yes, you can create a middleware and apply it for these 2 pages

We can implement it as an opt-in middleware, perhaps `guest-only` ? What do you think ?

**Comment by selemondev** [comment]
Yes. We can opt it in as a `guest-only` middleware.

**Comment by Hebilicious** [comment]
> Yes. We can opt it in as a `guest-only` middleware.

I think this is a good addition. Feel free to open a PR if you're already using one in your app 🙏🏽
