### ISSUE TITLE
Recommend using .env file, because runtimeConfig reads it automatically

### ISSUE THREAD

**Issue by thunfisch987** [Hebilicious/authjs-nuxt#53]
### Describe the feature

Hi, i think it would make sense to mention in the Readme / Documentation that Nuxt automatically maps a .env file to the runtimeConfig

This

```ts
// nuxt.config.ts
export default defineNuxtConfig({
    // ...
    runtimeConfig: {
        authJs: {
            secret: ''
        }
    }
    // ...
})
```

automatically maps to (if you have the NUXT_ infront)

```env
NUXT_AUTH_JS_SECRET=...
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
@thunfisch987, this is such a regular Nuxt feature, that being said we can add a line that explains this and references the official nuxt docs. PR welcome !
