### ISSUE TITLE
Session declaration merging

### ISSUE THREAD

**Issue by Shhu** [Hebilicious/authjs-nuxt#59]
### Describe the feature

Hi, i'm trying to merge the Session type with my own, 
I'm using `"@hebilicious/authjs-nuxt": "0.2.0-beta.5"` and `"@auth/core": "^0.10.0"`

I tryed : 
```
// as in https://authjs.dev/getting-started/typescript#main-module
declare module 'next-auth' {
  interface Session {
      user?: User
  } 
}
```
```
declare module 'authjs-nuxt' {
  interface Session {
      user?: User
  } 
}
```
```
declare module '#auth' {
  interface Session {
      user?: User
  } 
}
```
Without success, it would be nice if it was possible with `#auth`

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
The type is directly imported from auth.js `import type { Session } from "@auth/core/types"`, so this is possibly a feature that need to be open in auth.js directly

**Comment by Shhu** [comment]
At this moment the doc mention next-auth
https://authjs.dev/getting-started/typescript#main-module
So its probably work in progress sadly

**Comment by Hebilicious** [comment]
Actually could you try something like this ? 

```ts
import { DefaultSession } from '@auth/core/types';

declare module '@auth/core/types' {
	interface Session {
		user?: {
			id?: string;
			permissions?: string[];
		} & DefaultSession['user'];
	}
	interface User {
		permissions?: string[];
	}
}
```

**Comment by Shhu** [comment]
![image](https://github.com/Hebilicious/authjs-nuxt/assets/2306100/9c6fe7cb-6e7b-4a8d-bb65-baa7dd090831)
After reloading vscode to be sure

**Comment by Hebilicious** [comment]
please post a minimal reproduction and I'll investigate further, there might be something we can do at the module level.

**Comment by Shhu** [comment]
Repro : 
https://github.com/Shhu/auth-nuxt-repro-user-type

I used this augment https://github.com/Shhu/auth-nuxt-repro-user-type/blob/main/index.d.ts

It works server side : https://github.com/Shhu/auth-nuxt-repro-user-type/blob/main/server/api/auth/%5B...%5D.ts#L29

But fail client side : https://github.com/Shhu/auth-nuxt-repro-user-type/blob/main/pages/index.vue#L4
