### ISSUE TITLE
Typescript loses the middlewares

### ISSUE THREAD

**Issue by Shhu** [Hebilicious/authjs-nuxt#61]
### Environment

```
"@auth/core": "^0.10.0",
"@hebilicious/authjs-nuxt": "0.2.0-beta.5"
```

### Reproduction

https://github.com/Shhu/auth-nuxt-repro-signin-return/blob/main/pages/middlewareIssue.vue

### Describe the bug

Typescript loses the middlewares of the packages when a middleware is created in the middleware folder.

If you create a middleware in `/middleware` typescript no longer knows authjs-nuxt's middlewares (but it still works, types are probably overrode instead of augmented)

**Comment by Hebilicious** [comment]
This is very likely a nuxt or nuxt kit issue. Will investigate further.

**Comment by Hebilicious** [comment]
https://github.com/nuxt/nuxt/issues/22584
