### ISSUE TITLE
npm ERR! Conflicting peer dependency: @auth/core@0.9.0

### ISSUE THREAD

**Issue by cosbgn** [Hebilicious/authjs-nuxt#64]
### Environment

nuxt3.6

### Reproduction

npm i @auth/core will install v 0.10 which is incompatible with this library. Works locally but crashes while building on vercel-edge

### Describe the bug

```sh
npm ERR! Conflicting peer dependency: @auth/core@0.9.0
npm ERR! node_modules/@auth/core
npm ERR!   peer @auth/core@"^0.9.0" from @hebilicious/authjs-nuxt@0.2.0-beta.5
npm ERR!   node_modules/@hebilicious/authjs-nuxt
npm ERR!     dev @hebilicious/authjs-nuxt@"^0.2.0-beta.5" from the root project
```

**Comment by Hebilicious** [comment]
What is the issue with 0.10.0 ?

**Comment by cosbgn** [comment]
If you use:

```
    "@auth/core": "^0.10.2",
    "@hebilicious/authjs-nuxt": "^0.2.0-beta.5",
```
At least on vercel-edge the deployment fails immediately, these are the logs:

<img width="1280" alt="image" src="https://github.com/Hebilicious/authjs-nuxt/assets/17546283/84dbbc7b-7e6b-4b4a-b694-e6987fc58418">

**Comment by cosbgn** [comment]
There was a reference about this also [here](https://github.com/Hebilicious/authjs-nuxt/discussions/46#discussioncomment-6521460)

**Comment by cosbgn** [comment]
Fixed with `beta.6` thanks!
