### ISSUE TITLE
Login with Google doesn't work

### ISSUE THREAD

**Issue by cosbgn** [Hebilicious/authjs-nuxt#65]
### Environment

  "devDependencies": {
    "@auth/core": "^0.9.0",
    "@hebilicious/authjs-nuxt": "^0.2.0-beta.5",
    "nuxt": "^3.6"
  }

### Reproduction

Sorry for the many issues, but I'm trying to get this to work. My problem is that the login with google works on localhost but not on vercel-edge. It does nothing and it's really hard to debug.

Here is a reproduction: https://edgenu.vercel.app (credentials work fine, but google doesn't).
The code is at https://github.com/cosbgn/edgenu

### Describe the bug

Clicking on login with google does nothing when deployed. On local host it works perfectly.

### Additional context

Feel free to use these to test:

```
GOOGLE_CLIENT_ID="532721228880-jd6okhq4o9hv47fv4krbfvn5ggk81t2i.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET="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"
```

**Comment by Hebilicious** [comment]
This is a bug with setCookie headers will should be fixed in Nitro 2.6, you can use the edge channel as a workaround https://nitro.unjs.io/guide/getting-started#edge-release-channel

**Comment by Hebilicious** [comment]
Duplicate #51

**Comment by cosbgn** [comment]
Thanks a lot for your answer, I tried adding this (https://github.com/cosbgn/edgenu/blob/main/package.json) to my package.json but I keep getting the same issue https://edgenu.vercel.app - Am I missing something?

**Comment by Hebilicious** [comment]
@cosbgn It should work after you regenerate your lockfile.
However I've noticed some errors related to `vercel-edge` specifically (not to this module) 

https://nuxt-authjs-google.vercel.app/ <= vercel-edge work but the redirect hangs
https://authjs-cookie.pages.dev/ <= cloudflare_pages work without issues

**Comment by cosbgn** [comment]
@Hebilicious you are right. The login actually works, but without a hard refresh the session doesn't load.

Any idea of what could be causing the issue and if there is a workaround? Can I await login and then use something like `window.location.href` ?

**Comment by Hebilicious** [comment]
@cosbgn fixed in beta 8, make sure to use very recent nitropack and h3 

```
  "dependencies": {
    "@auth/core": "0.9.0",
    "h3": "1.8.0-rc.3",
    "nitropack": "npm:nitropack-edge@latest",
    "@hebilicious/authjs-nuxt": "0.2.0-beta.8"
  },
  "resolutions": {
    "h3": "1.8.0-rc.3",
    "nitropack": "npm:nitropack-edge@latest"
  }
  ```
