### ISSUE TITLE
Docs issue

### ISSUE THREAD

**Issue by louwers** [Hebilicious/authjs-nuxt#74]
This snippet from the docs needs fixing I think:

```
export default defineNuxtConfig({
...
  runtimeConfig: {
    authJs: {
      secret: process.env.NUXT_NEXTAUTH_SECRET // You can generate one with `openssl rand -base64 32`
    },
    github: {
      clientId: process.env.NUXT_GITHUB_CLIENT_ID,
      clientSecret: process.env.NUXT_GITHUB_CLIENT_SECRET
    },
    public: {
      authJs: {
        baseUrl: process.env.NUXT_NEXTAUTH_URL, // The base URL is used for the Origin Check in prod only
        verifyClientOnEveryRequest: true // whether to hit the /auth/session endpoint on every client request
      }
    }
  }
})
```

I am not sure if environment variables can be accessed there.

https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables

I was able to set the secret by setting the `NUXT_AUTH_JS_SECRET` environment variable. See Nuxt docs above.

**Comment by Hebilicious** [comment]
@louwers What needs fixing ? In this snippet, all env variable are prefixed by `NUXT_`which is necessary

**Comment by louwers** [comment]
As I understand it Nuxt 3 does not read the `runtimeConfig` values from the object you pass to `runtimeConfig`.

You should pass empty strings and set the environment variables accordingingly.

In particular the `authJs.secret` runtime config value will be read from `NUXT_AUTH_JS_SECRET` not `NUXT_NEXTAUTH_SECRET`. Again, this is explained in the Nuxt 3 docs. https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables

**Comment by Hebilicious** [comment]
> As I understand it Nuxt 3 does not read the `runtimeConfig` values from the object you pass to `runtimeConfig`. At least this did not work for me.
> 
> You should pass empty strings and set the environment variables accordingingly.
> 
> In particular the `authJs.secret` runtime config value will be read from `NUXT_AUTH_JS_SECRET` not `NUXT_NEXTAUTH_SECRET`. Again, this is explained in the Nuxt 3 docs. [nuxt.com/docs/guide/going-further/runtime-config#environment-variables](https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables)

It *does* reads them. If you can't use environment variable there this is a bug , do you have a reproduction?
Here's a very recent demo by Pi https://github.com/pi0/nuxt-openai-demo/blob/main/nuxt.config.ts

**Comment by louwers** [comment]
Alright, not sure why it didn't work for me.

I still think this is weird:

```
    github: {
      clientId: process.env.NUXT_GITHUB_CLIENT_ID,
```

because even if you set it to an empty string it will pick up `NUXT_GITHUB_CLIENT_ID`.

**Comment by Hebilicious** [comment]
> Alright, not sure why it didn't work for me.
> 
> I still think this should be changed:
> 
> ```
>     github: {
>       clientId: process.env.NUXT_GITHUB_CLIENT_ID,
> ```
> 
> because even if you set it to an empty string it will pick up `NUXT_GITHUB_CLIENT_ID`.

This is precisely why it's written there, to show people that they can this environment variable to override this value.
But the thing is, you don't *need* to use this environment varible, you can use `process.env.NUXT_GITHUB_MY_CLIENT` if you nuxt config and it will work too.

What exactly is unclear for you? How can the docs be improved?
