### ISSUE TITLE
Update to @auth/core 0.12.0

### ISSUE THREAD

**Issue by cosbgn** [Hebilicious/authjs-nuxt#82]
### Describe the feature

Hi, the current version is pinned to @auth/core@0.10 it would be great to pin it to the latest @auth/core@0.12. 

Would it be possible to unpin it and keep them completely separate? So that there is no need to update authjs-nuxt for every @auth/core new release. 

Thank you for your work, this library is now working perfectly on the edge!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
Thanks.

Not pinning would cause issues.
The module itself uses Authcore for its logic, so if you're using an older version or a newer version, something can go wrong. 
Renovate automatically updates auth core, but I do manual release to have some control over potential issues with newer versions.

Fyi this module will likely move to the authjs repo and be kept in sync that way.

**Comment by cosbgn** [comment]
Ok makes sense. Thanks for the info!
