### ISSUE TITLE
SignIn gives TypeError: crypto.getRandomValues is not a function

### ISSUE THREAD

**Issue by Q16solver** [Hebilicious/authjs-nuxt#99]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.5.1
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Package Manager:  npm@9.8.0
- User Config:      alias, css, build, nitro, vite, 
typescript, imports, runtimeConfig, modules, authJs, googleFonts, pinia, unocss
- Runtime Modules:  @hebilicious/authjs-nuxt@0.3.0, 
@nuxtjs/google-fonts@3.0.2, @pinia/nuxt@0.4.11, @unocss/nuxt@0.55.7, @vueuse/nuxt@10.4.1

### Reproduction

N/A

### Describe the bug

Running signIn function in production gives me a crypto module error for some reason

![image](https://github.com/Hebilicious/authjs-nuxt/assets/50786287/a0403349-2343-4355-ae2c-de9888844174)

### Logs

```sh
[auth][error][SignInError]: Read more at https://errors.authjs.dev#signinerror

[auth][cause]: TypeError: crypto.getRandomValues is not a function

at randomBytes (file:///app/.output/server/node_modules/oauth4webapi/build/index.js:237:24)

at Module.generateRandomCodeVerifier (file:///app/.output/server/node_modules/oauth4webapi/build/index.js:240:12)

at Object.create (file:///app/.output/server/node_modules/@auth/core/lib/oauth/checks.js:23:33)

at getAuthorizationUrl (file:///app/.output/server/node_modules/@auth/core/lib/oauth/authorization-url.js:57:57)

at processTicksAndRejections (node:internal/process/task_queues:96:5)

at async Module.signin (file:///app/.output/server/node_modules/@auth/core/lib/routes/signin.js:15:20)

at async AuthInternal (file:///app/.output/server/node_modules/@auth/core/lib/index.js:112:36)

at async Auth (file:///app/.output/server/node_modules/@auth/core/index.js:100:30)

at async file:///app/.output/server/chunks/nitro/node-server.mjs:7238:22

at async Object.handler (file:///app/.output/server/chunks/nitro/node-server.mjs:2380:19)

[auth][details]: {

"provider": "google"

}
```

**Comment by Hebilicious** [comment]
What is your production environment ? It should support `crypto.getRandomValues` as it's an auth.js requirement. This should be polyfilled by unenv or by this module directly.

**Comment by Q16solver** [comment]
I'm using [railway](https://railway.app) to deploy which has node v16 and npm v9. Though yeah, interestingly enough, it does say in the logs that it's polyfilled crypto module.

```
> nuxt preview

[log]

╭───────────────────────────────────Preview Mode─────────────────────────────────────╮

│                                                                                    │

│  You are running Nuxt production build in preview mode.                            │

│  For production deployments, please directly use node ./server/index.mjs command.  │

│                                                                                    │

│  Node.js:           v16.18.1                                                       │

│  Nitro Preset:      node-server                                                    │

│  Working directory: .output                                                        │

│                                                                                    │

╰────────────────────────────────────────────────────────────────────────────────────╯

[info] Loading `.env`. This will not be loaded when running the server in production.

[info] Starting preview command: `node ./server/index.mjs`

[log]

{

severity_local: 'NOTICE',

severity: 'NOTICE',

code: '42P06',

message: 'schema "drizzle" already exists, skipping',

file: 'schemacmds.c',

line: '118',

routine: 'CreateSchemaCommand'

}

{

severity_local: 'NOTICE',

severity: 'NOTICE',

code: '42P07',

message: 'relation "__drizzle_migrations" already exists, skipping',

file: 'parse_utilcmd.c',

line: '209',

routine: 'transformCreateStmt'

}

Polyfilling crypto...

Listening on http://[::]:6072

WebSocket Server is listening

Removing session
```

**Comment by Hebilicious** [comment]
> I'm using [railway](https://railway.app) to deploy which has node v16 and npm v9. Though yeah, interestingly enough, it does say in the logs that it's polyfilled crypto module.
> 
> ```
> > nuxt preview
> 
> [log]
> 
> ╭───────────────────────────────────Preview Mode─────────────────────────────────────╮
> 
> │                                                                                    │
> 
> │  You are running Nuxt production build in preview mode.                            │
> 
> │  For production deployments, please directly use node ./server/index.mjs command.  │
> 
> │                                                                                    │
> 
> │  Node.js:           v16.18.1                                                       │
> 
> │  Nitro Preset:      node-server                                                    │
> 
> │  Working directory: .output                                                        │
> 
> │                                                                                    │
> 
> ╰────────────────────────────────────────────────────────────────────────────────────╯
> 
> [info] Loading `.env`. This will not be loaded when running the server in production.
> 
> [info] Starting preview command: `node ./server/index.mjs`
> 
> [log]
> 
> {
> 
> severity_local: 'NOTICE',
> 
> severity: 'NOTICE',
> 
> code: '42P06',
> 
> message: 'schema "drizzle" already exists, skipping',
> 
> file: 'schemacmds.c',
> 
> line: '118',
> 
> routine: 'CreateSchemaCommand'
> 
> }
> 
> {
> 
> severity_local: 'NOTICE',
> 
> severity: 'NOTICE',
> 
> code: '42P07',
> 
> message: 'relation "__drizzle_migrations" already exists, skipping',
> 
> file: 'parse_utilcmd.c',
> 
> line: '209',
> 
> routine: 'transformCreateStmt'
> 
> }
> 
> Polyfilling crypto...
> 
> Listening on http://[::]:6072
> 
> WebSocket Server is listening
> 
> Removing session
> ```

The polyfill is something that I tried to do there https://github.com/Hebilicious/authjs-nuxt/blob/2100f25fd7de00095e00b330db3c3e29c22d1209/packages/authjs-nuxt/src/runtime/lib/server.ts#L9 , although I haven't tested it under all conditions, and I'm not sure it's working

For railway, it looks like you can use a more [recent](https://nixpacks.com/docs/providers/node) version of node, or even try out bun https://docs.railway.app/deploy/builds

I would also recommend that you never run your production app with Nuxt preview, instead run the built version with `node .output/server/index.mjs` https://nuxt.com/docs/getting-started/deployment

**Comment by Q16solver** [comment]
Yeah, seems like that was the issue, updated to use node 18 and works now, I'll also update to run the js file directly, thanks for the advice c:
